version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: act-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootP4ss
      MYSQL_DATABASE: transaction_db
      MYSQL_USER: act-user
      MYSQL_PASSWORD: actUserP4ss
    ports:
      - "3300:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    restart: always

  act-ms-auth:
    build:
      context: .
      dockerfile: act-ms-auth/Dockerfile
    ports:
      - "5001:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
      ASPNETCORE_URLS: "http://*:8081"
    depends_on:
      - mysql
      - redis
      - rabbitmq

  act-ms-consolidation:
    build:
      context: .
      dockerfile: act-ms-consolidation/Dockerfile
    deploy:
      replicas: 2
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
      ASPNETCORE_URLS: "http://*:8082"
    depends_on:
      - mysql
      - redis
      - rabbitmq

  act-ms-transaction:
    build:
      context: .
      dockerfile: act-ms-transaction/Dockerfile
    deploy:
      replicas: 2
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
      ASPNETCORE_URLS: "http://*:8083"
    depends_on:
      - mysql
      - redis
      - rabbitmq

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - act-ms-consolidation
      - act-ms-transaction
